apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: poll
  labels:
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: poll
          image: epitechcontent/t-dop-600-poll:k8s
          ports:
            - containerPort: 80
              name: poll
          resources:
            limits: 
              memory: "128Mi"
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_HOST
      restartPolicy: Always