apiVersion: v1
kind: ConfigMap
metadata:
 name: postgres-config
 namespace: default
data:
  POSTGRES_HOST: postgres_host
  POSTGRES_PORT: postgres_port
  POSTGRES_DB: postgres_db
  POSTGRES_USER: postgres_user